import express, { type Express } from "express";
import cors from "cors";
import helmet from "helmet";
import pinoHttp from "pino-http";
import rateLimit from "express-rate-limit";
import router from "./routes";
import { logger } from "./lib/logger";

const app: Express = express();

// ── Security headers (helmet) ──────────────────────────────────────────────────
//
// Applied before every other middleware so security headers are present even
// on error responses generated by rate-limiting or the logger.
//
// ARCHITECTURE NOTE: Express only handles /api/* requests. The frontend HTML
// is served by Replit's static handler, so these headers reach API responses
// only — not the HTML document itself. The HTML document is protected via the
// <meta http-equiv="Content-Security-Policy"> tag in index.html.
//
const isProduction = process.env.NODE_ENV === "production";

app.use(
  helmet({
    // ── Content-Security-Policy ────────────────────────────────────────────
    // The API server emits JSON exclusively. A maximally restrictive policy
    // prevents a browser from treating a JSON response as a renderable
    // document if it is ever loaded in a frame or top-level navigation.
    //   default-src 'none'  — no scripts, styles, images, or connections needed
    //   frame-ancestors     — API responses must never be framed (belt-and-
    //                         suspenders alongside X-Frame-Options: DENY below)
    //   form-action 'self'  — a JSON response should never be a form target
    contentSecurityPolicy: {
      // useDefaults: false — helmet v7+ merges with its own default directives
      // unless explicitly disabled. We want the minimum viable policy for a
      // JSON API: no rendering surface, no frames, no forms.
      useDefaults: false,
      directives: {
        defaultSrc:     ["'none'"],
        frameAncestors: ["'none'"],
        formAction:     ["'self'"],
      },
    },

    // ── X-Frame-Options: DENY ──────────────────────────────────────────────
    // Belt-and-suspenders alongside frame-ancestors 'none'. Older browsers
    // that pre-date CSP2 still respect this header; modern ones honour both.
    frameguard: { action: "deny" },

    // ── Strict-Transport-Security ──────────────────────────────────────────
    // Enabled in production only. Replit terminates TLS at its edge proxy
    // before forwarding plain HTTP to the Express process, so the process
    // itself sees HTTP — we still emit HSTS so the browser remembers to
    // upgrade future direct connections without a round-trip.
    // 63 072 000 s = 2 years, the minimum required for HSTS preload list
    // submission (https://hstspreload.org).
    hsts: isProduction
      ? { maxAge: 63_072_000, includeSubDomains: true, preload: true }
      : false,

    // ── Referrer-Policy ────────────────────────────────────────────────────
    // Sends the full URL to same-origin requests (server logs stay useful)
    // but strips path and query for cross-origin requests, so internal API
    // paths are never leaked to external CDNs (API-Football, Google Fonts).
    referrerPolicy: { policy: "strict-origin-when-cross-origin" },

    // ── Cross-Origin-Resource-Policy ───────────────────────────────────────
    // "cross-origin" is intentional: the API is consumed cross-origin by the
    // Vite dev server proxy and by the Replit static-proxy in production.
    // "same-origin" would block those reads even when CORS allows them.
    // The CORS middleware above remains the authority on which origins may
    // actually read responses.
    crossOriginResourcePolicy: { policy: "cross-origin" },

    // ── Cross-Origin-Opener-Policy ─────────────────────────────────────────
    // Isolates the browsing context from cross-origin popups. Safe for a
    // JSON API — no popup or postMessage flows are used.
    crossOriginOpenerPolicy: { policy: "same-origin" },

    // ── X-Content-Type-Options: nosniff ───────────────────────────────────
    // Prevents browsers from MIME-sniffing a JSON response as HTML or JS.
    // Helmet enables this by default; listed explicitly for auditability.
    xContentTypeOptions: true,

    // ── X-XSS-Protection ─────────────────────────────────────────────────
    // The legacy XSS auditor is disabled in all modern browsers and can
    // introduce its own vulnerabilities in older ones. Helmet 7+ sets
    // "X-XSS-Protection: 0" by default, which we keep.
    xXssProtection: false,

    // ── DNS Prefetch Control ──────────────────────────────────────────────
    dnsPrefetchControl: { allow: false },

    // ── X-Permitted-Cross-Domain-Policies ─────────────────────────────────
    permittedCrossDomainPolicies: { permittedPolicies: "none" },
  }),
);

// ── CORS ──────────────────────────────────────────────────────────────────────

// Build the CORS origin allowlist from the environment.
// ALLOWED_ORIGINS is a comma-separated list of exact origins, e.g.
//   ALLOWED_ORIGINS=https://example.com,https://app.example.com
// In development on Replit we also accept the proxied dev domain automatically.
function buildAllowedOrigins(): string[] {
  const origins: string[] = [];

  const fromEnv = process.env.ALLOWED_ORIGINS;
  if (fromEnv) {
    origins.push(...fromEnv.split(",").map((o) => o.trim()).filter(Boolean));
  }

  // Replit dev domain — present in the workspace, absent in production deploys.
  const replitDev = process.env.REPLIT_DEV_DOMAIN;
  if (replitDev) {
    origins.push(`https://${replitDev}`);
  }

  // Replit deployment domains (space-separated list set by the deploy platform).
  const replitDomains = process.env.REPLIT_DOMAINS;
  if (replitDomains) {
    for (const d of replitDomains.split(/[\s,]+/).filter(Boolean)) {
      origins.push(`https://${d}`);
    }
  }

  return origins;
}

const allowedOrigins = buildAllowedOrigins();

app.use(
  cors({
    origin(origin, callback) {
      // Allow server-to-server requests (no Origin header) and same-origin
      // requests, plus any explicitly allowlisted origin.
      if (!origin || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error(`CORS: origin not allowed — ${origin}`));
      }
    },
    credentials: true,
  }),
);

// Global rate limiter: 300 requests per minute per IP for all public routes.
// Tighter limits can be applied per-route as needed.
const globalLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 300,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many requests, please try again later." },
});

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);
app.use(globalLimiter);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use("/api", router);

export default app;
